import { createFileRoute } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { BOT_TEMPLATES } from '@/lib/templates';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Calendar } from '@/components/ui/calendar';
import { Users, Search, ChevronLeft, ChevronRight, MessageCircle, Send, Pencil, CalendarDays, RefreshCw, Minus, Plus, Smartphone, Copy, PlusCircle, Gift, Trash2 } from 'lucide-react';
import { ServerBadge } from '@/components/ServerBadge';
import { NewClientDialog } from '@/components/NewClientDialog';
import { useState } from 'react';
import { format, parseISO } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { toZonedTime } from 'date-fns-tz';
import { toast } from 'sonner';

export const Route = createFileRoute('/_authenticated/clientes')({ component: ClientesPage });
type Client = any;
type Option = { id: string; name: string; price?: number; valor?: number };
type AppMode = 'view' | 'edit' | 'new';
type RenewMode = 'normal' | 'bonus';

const APP_CATALOG = [
  { name: 'Ibo Pro', url: 'https://iboproapp.com/manage-playlists/login/' },
  { name: 'Ibo Player', url: 'https://iboplayer.com/device/login' },
  { name: 'Bob Player', url: 'https://bobplayer.com/device/login' },
] as const;
const SERVER_PANELS = [
  { names: ['uniplay'], url: 'https://searchdefense.top/#/login' },
  { names: ['goat'], url: 'https://goatnt.com/' },
  { names: ['p2braz', 'p2bras', 'p2 braz', 'p2 bras'], url: 'https://painel.fun/lock?redirect=%2Fusers' },
] as const;

function getAppUrl(name: string) { return APP_CATALOG.find((app) => app.name.toLowerCase() === String(name || '').toLowerCase())?.url; }
function getServerPanelUrl(name: string) { const normalized = String(name || '').trim().toLowerCase(); return SERVER_PANELS.find((server) => server.names.some((alias) => alias === normalized))?.url; }
function getServerPanelClass(name: string) {
  if (/uniplay/i.test(name)) return 'bg-sky-500/10 text-sky-500 border-sky-500/30 hover:bg-sky-500/15';
  if (/goat/i.test(name)) return 'bg-orange-500/10 text-orange-500 border-orange-500/30 hover:bg-orange-500/15';
  if (/p2braz/i.test(name)) return 'bg-purple-500/10 text-purple-400 border-purple-500/30 hover:bg-purple-500/15';
  return '';
}
function addDaysISO(iso: string, days: number) { const [y, m, d] = iso.split('-').map(Number) as [number, number, number]; const dt = new Date(Date.UTC(y, m - 1, d)); dt.setUTCDate(dt.getUTCDate() + days); return dt.toISOString().slice(0, 10); }

function ClientesPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [planFilter, setPlanFilter] = useState('');
  const [serverFilter, setServerFilter] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [selectedClient, setSelectedClient] = useState<Client>(null);
  const [isMessageOpen, setIsMessageOpen] = useState(false);
  const [isEditOpen, setIsEditOpen] = useState(false);
  const [isRenewOpen, setIsRenewOpen] = useState(false);
  const [isRenewSuccessOpen, setIsRenewSuccessOpen] = useState(false);
  const [isAppOpen, setIsAppOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [appMode, setAppMode] = useState<AppMode>('view');
  const [renewDate, setRenewDate] = useState('');
  const [renewMode, setRenewMode] = useState<RenewMode>('normal');
  const [isRenewing, setIsRenewing] = useState(false);
  const [isAppSaving, setIsAppSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isDatePickerOpen, setIsDatePickerOpen] = useState(false);
  const [plans, setPlans] = useState<Option[]>([]);
  const [servers, setServers] = useState<Option[]>([]);
  const [editForm, setEditForm] = useState({ nome: '', whatsapp: '', vencimento: '', plano_id: '', desconto: '', servidores_ids: [] as string[] });
  const [appForm, setAppForm] = useState({ id: '', app_nome: '', mac_address: '', app_key: '' });
  const itemsPerPage = 10;

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['clients-active', searchTerm, planFilter, serverFilter, currentPage], placeholderData: (prev) => prev,
    queryFn: async () => {
      const nowBr = toZonedTime(new Date(), 'America/Sao_Paulo'); nowBr.setHours(0, 0, 0, 0); const todayStr = format(nowBr, 'yyyy-MM-dd');
      const [{ data: serversData }, { data: templates }, { data: filterPlans }] = await Promise.all([
        supabase.from('servidores_iptv').select('id, name').order('name'),
        supabase.from('templates_whatsapp' as any).select('*').order('nome', { ascending: true }),
        supabase.from('plans').select('id, name').eq('active', true).order('name'),
      ]);
      let query = supabase.from('clientes').select('*, plans(name, price)', { count: 'exact' }).gte('vencimento', todayStr).order('vencimento', { ascending: true });
      if (searchTerm) query = query.ilike('nome', `%${searchTerm}%`); if (planFilter) query = query.eq('plano_id', planFilter); if (serverFilter) query = query.contains('servidores_ids', [serverFilter]);
      const from = (currentPage - 1) * itemsPerPage; const { data: clients, count, error } = await query.range(from, from + itemsPerPage - 1); if (error) throw error;
      const clientIds = (clients || []).map((client) => client.id); let devices: any[] = [];
      if (clientIds.length) { const { data: deviceRows, error: deviceError } = await supabase.from('dispositivos').select('id, cliente_id, app_nome, mac_address, app_key, created_at').in('cliente_id', clientIds).order('created_at', { ascending: true }); if (deviceError) throw deviceError; devices = deviceRows || []; }
      const processedClients = (clients || []).map((client) => ({ ...client, serverName: (client.servidores_ids || []).map((id: string) => serversData?.find((server) => server.id === id)?.name).filter(Boolean).join(', ') || 'N/A', templates: templates || [], devices: devices.filter((device) => device.cliente_id === client.id) }));
      return { clients: processedClients, totalCount: count || 0, filterPlans: filterPlans || [], filterServers: serversData || [] };
    },
  });
  const totalPages = Math.ceil((data?.totalCount || 0) / itemsPerPage);

  const openMessageModal = (client: Client) => { if (!client.whatsapp) { toast.error('Cliente sem WhatsApp cadastrado.'); return; } setSelectedClient(client); setIsMessageOpen(true); };
  const openApp = (client: Client) => { setSelectedClient(client); setAppForm({ id: '', app_nome: '', mac_address: '', app_key: '' }); setAppMode('view'); setIsAppOpen(true); };
  const openDelete = (client: Client) => { setSelectedClient(client); setIsDeleteOpen(true); };
  const startNewApp = () => { setAppMode('new'); setAppForm({ id: '', app_nome: '', mac_address: '', app_key: '' }); };
  const startEditApp = (device: any) => { setAppMode('edit'); setAppForm({ id: device.id, app_nome: device.app_nome || '', mac_address: device.mac_address || '', app_key: device.app_key || '' }); };
  const copyValue = async (value: string, label: string) => { if (!value) return; try { await navigator.clipboard.writeText(value); toast.success(`${label} copiado.`); } catch { toast.error(`Não foi possível copiar ${label}.`); } };

  async function confirmDelete() { if (!selectedClient || isDeleting) return; setIsDeleting(true); try { const { error } = await supabase.from('clientes').delete().eq('id', selectedClient.id); if (error) throw error; toast.success(`${selectedClient.nome} excluído.`); setIsDeleteOpen(false); setSelectedClient(null); await refetch(); } catch (error) { console.error(error); toast.error('Não foi possível excluir o cliente.'); } finally { setIsDeleting(false); } }
  async function saveAppData() {
    if (!selectedClient || isAppSaving) return; if (!appForm.app_nome.trim()) { toast.error('Informe o aplicativo.'); return; } setIsAppSaving(true);
    try { const payload = { cliente_id: selectedClient.id, app_nome: appForm.app_nome.trim(), mac_address: appForm.mac_address.trim(), app_key: appForm.app_key.trim() || null }; if (appForm.id) { const { error } = await supabase.from('dispositivos').update(payload).eq('id', appForm.id); if (error) throw error; } else { const { error } = await supabase.from('dispositivos').insert(payload); if (error) throw error; } toast.success(appForm.id ? 'Dados do aplicativo atualizados.' : 'Aplicativo adicionado.'); await refetch(); setAppMode('view'); } catch (error) { console.error(error); toast.error('Não foi possível salvar os dados do aplicativo.'); } finally { setIsAppSaving(false); }
  }
  const handleSendMessage = (template: any) => { if (!selectedClient) return; const firstName = selectedClient.nome.split(' ')[0]; const valor = selectedClient.plans ? (Number(selectedClient.plans.price) - Number(selectedClient.desconto || 0)).toFixed(2) : '0.00'; const vencimentoBr = selectedClient.vencimento?.includes('-') ? format(parseISO(selectedClient.vencimento), 'dd/MM/yyyy') : selectedClient.vencimento; const message = template.mensagem.replace(/{nome}/g, selectedClient.nome).replace(/{primeiro_nome}/g, firstName).replace(/{vencimento}/g, vencimentoBr || '').replace(/{valor}/g, `R$ ${valor}`); const phoneRaw = selectedClient.whatsapp.replace(/\D/g, ''); const phone = phoneRaw.startsWith('55') ? phoneRaw : `55${phoneRaw}`; window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`, '_blank'); setIsMessageOpen(false); };
  function sendRenewalMessage() { if (!selectedClient?.whatsapp || !selectedClient?.vencimento) { toast.error('Cliente sem WhatsApp cadastrado.'); return; } const firstName = (selectedClient.nome || 'Cliente').trim().split(' ')[0] || 'Cliente'; const brDate = format(parseISO(selectedClient.vencimento), 'dd/MM/yyyy'); const message = BOT_TEMPLATES.CONFIRMACAO(firstName, brDate); const phoneRaw = selectedClient.whatsapp.replace(/\D/g, ''); const phone = phoneRaw.startsWith('55') ? phoneRaw : `55${phoneRaw}`; window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`, '_blank'); setIsRenewSuccessOpen(false); }
  function openRenew(client: Client) { const current = String(client.vencimento || '').slice(0, 10); if (!current) { toast.error('Cliente sem vencimento válido.'); return; } setSelectedClient(client); setRenewDate(addDaysISO(current, 30)); setRenewMode('normal'); setIsRenewOpen(true); }
  async function confirmRenew(mode: RenewMode = renewMode) {
    if (!selectedClient || !renewDate || isRenewing) return; setIsRenewing(true);
    try { const { data: authData } = await supabase.auth.getUser(); const userId = authData.user?.id; if (!userId) throw new Error('Usuário não autenticado.'); const [{ data: plan, error: planError }, { data: serverRows, error: serverError }] = await Promise.all([supabase.from('plans').select('price').eq('id', selectedClient.plano_id).single(), selectedClient.servidores_ids?.length ? supabase.from('servidores_iptv').select('valor').in('id', selectedClient.servidores_ids) : Promise.resolve({ data: [], error: null } as any)]); if (planError || !plan) throw planError || new Error('Plano não encontrado.'); if (serverError) throw serverError; const valorNormal = Math.max(0, Number(plan.price || 0) - Number(selectedClient.desconto || 0)); const valorEntrada = mode === 'bonus' ? 0 : valorNormal; const totalCusto = (serverRows || []).reduce((sum: number, server: any) => sum + Number(server.valor || 0), 0); const todayBr = format(toZonedTime(new Date(), 'America/Sao_Paulo'), 'yyyy-MM-dd'); const { error: renewalError } = await supabase.from('renovacoes').insert({ user_id: userId, cliente_id: selectedClient.id, plano_id: selectedClient.plano_id, valor: valorEntrada, desconto: Number(selectedClient.desconto || 0), vencimento_anterior: selectedClient.vencimento, novo_vencimento: renewDate, data_renovacao: new Date().toISOString() }); if (renewalError) throw renewalError; const descricao = mode === 'bonus' ? `Bônus por indicação — ${selectedClient.nome}` : `Renovação cliente ${selectedClient.id}`; const { error: transactionError } = await supabase.from('transacoes').insert({ user_id: userId, cliente_id: selectedClient.id, tipo: mode === 'bonus' ? 'saida' : 'entrada', entrada: valorEntrada, custo: totalCusto, valor: valorEntrada, data: todayBr, descricao, serv_id: selectedClient.servidores_ids?.[0] || null }); if (transactionError) throw transactionError; const { error: updateError } = await supabase.from('clientes').update({ vencimento: renewDate, status: 'ativo' }).eq('id', selectedClient.id); if (updateError) throw updateError; setSelectedClient({ ...selectedClient, vencimento: renewDate }); setIsRenewOpen(false); setIsRenewSuccessOpen(true); toast.success(mode === 'bonus' ? `Bônus aplicado a ${selectedClient.nome}.` : `${selectedClient.nome} renovado.`); await refetch(); } catch (error) { console.error(error); toast.error('Não foi possível renovar o cliente.'); } finally { setIsRenewing(false); }
  }
  async function openEdit(client: Client) { const [{ data: planData }, { data: serverData }] = await Promise.all([supabase.from('plans').select('id, name, price').eq('active', true).order('name'), supabase.from('servidores_iptv').select('id, name').eq('active', true).order('name')]); setPlans(planData || []); setServers(serverData || []); setSelectedClient(client); setEditForm({ nome: client.nome || '', whatsapp: client.whatsapp || '', vencimento: client.vencimento || '', plano_id: client.plano_id || '', desconto: client.desconto == null ? '' : String(client.desconto), servidores_ids: client.servidores_ids || [] }); setIsEditOpen(true); }
  async function saveEdit() { if (!selectedClient) return; if (!editForm.nome.trim() || !editForm.vencimento || !editForm.plano_id || editForm.servidores_ids.length === 0) { toast.error('Preencha nome, vencimento, plano e servidor.'); return; } const desconto = Number(editForm.desconto.replace(',', '.') || 0); if (!Number.isFinite(desconto) || desconto < 0) { toast.error('Desconto inválido.'); return; } const { error } = await supabase.from('clientes').update({ nome: editForm.nome.trim(), whatsapp: editForm.whatsapp.trim(), vencimento: editForm.vencimento, plano_id: editForm.plano_id, desconto, servidores_ids: editForm.servidores_ids }).eq('id', selectedClient.id); if (error) { toast.error('Não foi possível salvar o cliente.'); return; } toast.success('Cliente atualizado.'); setIsEditOpen(false); await refetch(); }
  function toggleEditServer(id: string) { setEditForm((form) => ({ ...form, servidores_ids: form.servidores_ids.includes(id) ? form.servidores_ids.filter((serverId) => serverId !== id) : [...form.servidores_ids, id] })); }

  const Actions = ({ client, mobile = false }: { client: Client; mobile?: boolean }) => <div className="flex items-center justify-end gap-2"><Button size="icon" variant="outline" title="Editar" onClick={() => openEdit(client)} className={`${mobile ? 'h-11 w-11' : 'h-9 w-9'} rounded-xl`}><Pencil size={mobile ? 18 : 16} /></Button><Button size="icon" variant="outline" title="Renovar" onClick={() => openRenew(client)} className={`${mobile ? 'h-11 w-11' : 'h-9 w-9'} rounded-xl`}><RefreshCw size={mobile ? 18 : 16} /></Button><Button size="icon" variant="outline" title="Dados do aplicativo" onClick={() => openApp(client)} className={`${mobile ? 'h-11 w-11' : 'h-9 w-9'} rounded-xl ${client.devices?.length ? 'text-primary border-primary/30 bg-primary/5' : ''}`}><Smartphone size={mobile ? 18 : 16} /></Button><Button size="icon" title="Mensagem" onClick={() => openMessageModal(client)} className={`${mobile ? 'h-11 w-11' : 'h-9 w-9'} rounded-xl bg-emerald-500 text-white hover:bg-emerald-600`}><MessageCircle size={mobile ? 19 : 17} /></Button><Button size="icon" variant="outline" title="Excluir cliente" onClick={() => openDelete(client)} className={`${mobile ? 'h-11 w-11' : 'h-9 w-9'} rounded-xl text-rose-500 border-rose-500/30 hover:bg-rose-500/10 hover:text-rose-500`}><Trash2 size={mobile ? 18 : 16} /></Button></div>;
  const selectedDevices = data?.clients?.find((client: Client) => client.id === selectedClient?.id)?.devices || [];
  const selectedServers = (data?.filterServers || []).filter((server: Option) => selectedClient?.servidores_ids?.includes(server.id)).map((server: Option) => ({ ...server, panelUrl: getServerPanelUrl(server.name) })).filter((server: any) => server.panelUrl);

  return <div className="p-4 md:p-8 max-w-[1200px] mx-auto space-y-6 animate-in fade-in duration-500">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div className="flex items-center justify-between gap-3"><h1 className="text-3xl font-black tracking-tighter uppercase flex items-center gap-2"><Users className="text-primary" />Clientes</h1><NewClientDialog /></div><div className="grid grid-cols-2 gap-2 w-full md:flex md:w-auto"><div className="relative col-span-2 w-full md:w-72"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground h-4 w-4" /><Input placeholder="Buscar por nome..." className="pl-10 bg-card border-border rounded-xl h-11" value={searchTerm} onChange={(e) => { setSearchTerm(e.target.value); setCurrentPage(1); }} /></div><select className="h-11 min-w-0 rounded-xl border border-border bg-card px-3 text-sm" value={planFilter} onChange={(e) => { setPlanFilter(e.target.value); setCurrentPage(1); }}><option value="">Todos os planos</option>{data?.filterPlans?.map((plan: Option) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select><select className="h-11 min-w-0 rounded-xl border border-border bg-card px-3 text-sm" value={serverFilter} onChange={(e) => { setServerFilter(e.target.value); setCurrentPage(1); }}><option value="">Todos os servidores</option>{data?.filterServers?.map((server: Option) => <option key={server.id} value={server.id}>{server.name}</option>)}</select></div></div>
    {isLoading ? <div className="bg-card border border-border rounded-2xl p-8 text-center text-muted-foreground">Carregando clientes...</div> : !data?.clients?.length ? <div className="bg-card border border-border rounded-2xl p-8 text-center text-muted-foreground">Nenhum cliente ativo encontrado.</div> : <><div className="hidden md:block bg-card border border-border rounded-2xl overflow-hidden shadow-sm"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Servidor/App</TableHead><TableHead>Vencimento</TableHead><TableHead className="text-right">Ação</TableHead></TableRow></TableHeader><TableBody>{data.clients.map((client: Client) => <TableRow key={client.id}><TableCell className="font-bold">{client.nome}</TableCell><TableCell><ServerBadge name={client.serverName} /></TableCell><TableCell><span className="text-primary font-bold font-mono">{client.vencimento?.includes('-') ? format(parseISO(client.vencimento), 'dd/MM/yyyy') : client.vencimento}</span></TableCell><TableCell><Actions client={client} /></TableCell></TableRow>)}</TableBody></Table></div><div className="md:hidden space-y-4">{data.clients.map((client: Client) => <div key={client.id} className="bg-card border border-border rounded-2xl p-4 shadow-sm space-y-3"><h3 className="font-black text-lg uppercase">{client.nome}</h3><ServerBadge name={client.serverName} /><div className="text-sm"><span className="text-muted-foreground">Vencimento: </span><span className="text-primary font-bold font-mono">{client.vencimento?.includes('-') ? format(parseISO(client.vencimento), 'dd/MM/yyyy') : client.vencimento}</span></div><Actions client={client} mobile /></div>)}</div>{totalPages > 1 && <div className="flex items-center justify-between"><Button variant="outline" size="sm" disabled={currentPage === 1} onClick={() => setCurrentPage((p) => p - 1)}><ChevronLeft size={16} />Anterior</Button><span className="text-sm">{currentPage} / {totalPages}</span><Button variant="outline" size="sm" disabled={currentPage === totalPages} onClick={() => setCurrentPage((p) => p + 1)}>Próximo<ChevronRight size={16} /></Button></div>}</>}

    <Dialog open={isDeleteOpen} onOpenChange={setIsDeleteOpen}><DialogContent className="max-w-sm rounded-2xl"><DialogHeader><DialogTitle>Excluir cliente?</DialogTitle><DialogDescription>Excluir <strong>{selectedClient?.nome}</strong> definitivamente? Esta ação não pode ser desfeita.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => setIsDeleteOpen(false)}>Cancelar</Button><Button variant="destructive" disabled={isDeleting} onClick={confirmDelete}>{isDeleting ? 'Excluindo...' : 'Excluir'}</Button></div></DialogContent></Dialog>
    <Dialog open={isAppOpen} onOpenChange={setIsAppOpen}><DialogContent onOpenAutoFocus={(e) => e.preventDefault()} className="max-w-sm rounded-2xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle className="flex items-center gap-2"><Smartphone size={20} />Dados do aplicativo</DialogTitle><DialogDescription>{selectedClient?.nome}</DialogDescription></DialogHeader>{appMode === 'view' ? <div className="space-y-3">{selectedServers.map((server: any) => <Button key={server.id} variant="outline" onClick={() => window.open(server.panelUrl, '_blank')} className={`w-full ${getServerPanelClass(server.name)}`}>{server.name}</Button>)}{selectedDevices.map((device: any) => <div key={device.id} className="rounded-2xl border p-4 space-y-2"><div className="flex justify-between"><b>{device.app_nome}</b><Button size="icon" variant="outline" onClick={() => startEditApp(device)}><Pencil size={16} /></Button></div>{device.mac_address && <div className="flex justify-between"><span>{device.mac_address}</span><Button size="icon" variant="outline" onClick={() => copyValue(device.mac_address, 'MAC')}><Copy size={16} /></Button></div>}{device.app_key && <div className="flex justify-between"><span>{device.app_key}</span><Button size="icon" variant="outline" onClick={() => copyValue(device.app_key, 'Key')}><Copy size={16} /></Button></div>}{getAppUrl(device.app_nome) && <Button variant="outline" className="w-full" onClick={() => window.open(getAppUrl(device.app_nome), '_blank')}>Acessar painel</Button>}</div>)}<Button variant="outline" className="w-full" onClick={startNewApp}><PlusCircle size={17} className="mr-2" />Adicionar aplicativo</Button></div> : <div className="space-y-4"><label>Aplicativo<select className="mt-1 w-full h-10 rounded-md border bg-background px-3" value={appForm.app_nome} onChange={(e) => setAppForm((f) => ({ ...f, app_nome: e.target.value }))}><option value="">Selecione</option>{APP_CATALOG.map((a) => <option key={a.name}>{a.name}</option>)}</select></label><Input placeholder="MAC" value={appForm.mac_address} onChange={(e) => setAppForm((f) => ({ ...f, mac_address: e.target.value }))} /><Input placeholder="Key" value={appForm.app_key} onChange={(e) => setAppForm((f) => ({ ...f, app_key: e.target.value }))} /><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => setAppMode('view')}>Cancelar</Button><Button onClick={saveAppData}>Salvar</Button></div></div>}</DialogContent></Dialog>
    <Dialog open={isRenewOpen} onOpenChange={setIsRenewOpen}><DialogContent className="max-w-sm rounded-2xl"><DialogHeader><DialogTitle>{selectedClient?.nome}</DialogTitle><DialogDescription>Ajuste a nova data e escolha o tipo de renovação.</DialogDescription></DialogHeader><div className="grid grid-cols-[52px_1fr_52px] gap-2 py-4"><Button variant="outline" onClick={() => setRenewDate((d) => addDaysISO(d, -1))}><Minus /></Button><div className="flex items-center justify-center border rounded-xl font-bold">{renewDate ? format(parseISO(renewDate), 'dd/MM/yyyy') : ''}</div><Button variant="outline" onClick={() => setRenewDate((d) => addDaysISO(d, 1))}><Plus /></Button></div><Button className="w-full mb-2" disabled={isRenewing} onClick={() => confirmRenew('normal')}><RefreshCw size={16} className="mr-2" />Renovação normal</Button><Button variant="outline" className="w-full" disabled={isRenewing} onClick={() => confirmRenew('bonus')}><Gift size={16} className="mr-2" />Bônus por indicação</Button></DialogContent></Dialog>
    <Dialog open={isRenewSuccessOpen} onOpenChange={setIsRenewSuccessOpen}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Renovado — {selectedClient?.nome}</DialogTitle></DialogHeader><Button onClick={sendRenewalMessage}><MessageCircle size={16} className="mr-2" />Enviar mensagem</Button></DialogContent></Dialog>
    <Dialog open={isMessageOpen} onOpenChange={setIsMessageOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Selecionar Mensagem</DialogTitle></DialogHeader><div className="grid gap-3">{selectedClient?.templates?.map((template: any) => <Button key={template.id} variant="outline" onClick={() => handleSendMessage(template)}>{template.nome}<Send size={16} /></Button>)}</div></DialogContent></Dialog>

    <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}><DialogContent onOpenAutoFocus={(e) => e.preventDefault()} className="max-w-md rounded-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle className="text-xl font-black uppercase tracking-tighter">Editar Cliente</DialogTitle><DialogDescription>Altere os dados do cadastro sem sair do Gestor.</DialogDescription></DialogHeader><div className="space-y-4 py-3"><label className="block text-sm font-medium">Nome<Input className="mt-1" value={editForm.nome} onChange={(e) => setEditForm((f) => ({ ...f, nome: e.target.value }))} /></label><label className="block text-sm font-medium">WhatsApp<Input className="mt-1" value={editForm.whatsapp} onChange={(e) => setEditForm((f) => ({ ...f, whatsapp: e.target.value }))} /></label><div><p className="text-sm font-medium mb-2">Vencimento</p><Button type="button" variant="outline" onClick={() => setIsDatePickerOpen(true)} className="w-full h-11 justify-between rounded-xl"><span>{editForm.vencimento ? format(parseISO(editForm.vencimento), 'dd/MM/yyyy') : 'Selecione a data'}</span><CalendarDays size={16} /></Button></div><label className="block text-sm font-medium">Plano<select className="mt-1 w-full h-10 rounded-md border bg-background px-3" value={editForm.plano_id} onChange={(e) => setEditForm((f) => ({ ...f, plano_id: e.target.value }))}><option value="">Selecione</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} — {money(plan.price || 0)}</option>)}</select></label><label className="block text-sm font-medium">Desconto (R$)<Input className="mt-1" value={editForm.desconto} onChange={(e) => setEditForm((f) => ({ ...f, desconto: e.target.value }))} /></label><div><p className="text-sm font-medium mb-2">Servidor <span className="font-normal text-muted-foreground">(selecione um ou mais)</span></p><div className="grid grid-cols-3 gap-2">{servers.map((server) => { const selected = editForm.servidores_ids.includes(server.id); return <button key={server.id} type="button" onClick={() => toggleEditServer(server.id)} aria-pressed={selected} className={`flex min-w-0 items-center justify-center gap-1 rounded-xl border px-2 py-2 text-xs font-semibold transition-colors ${selected ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-background text-foreground hover:bg-muted/50'}`}><span className="truncate">{server.name}</span>{selected && <span className="text-sm leading-none">✓</span>}</button>; })}</div></div></div><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => setIsEditOpen(false)}>Cancelar</Button><Button onClick={saveEdit}>Salvar alterações</Button></div></DialogContent></Dialog>
    <Dialog open={isDatePickerOpen} onOpenChange={setIsDatePickerOpen}><DialogContent className="w-[calc(100%-2rem)] max-w-sm rounded-2xl p-4"><DialogHeader><DialogTitle>Data de vencimento</DialogTitle></DialogHeader><div className="flex justify-center"><Calendar mode="single" locale={ptBR} selected={editForm.vencimento ? parseISO(editForm.vencimento) : undefined} onSelect={(date) => { if (date) { setEditForm((f) => ({ ...f, vencimento: format(date, 'yyyy-MM-dd') })); setIsDatePickerOpen(false); } }} /></div></DialogContent></Dialog>
  </div>;
}
function money(value: number) { return `R$ ${Number(value).toFixed(2).replace('.', ',')}`; }
