// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

async function registerNewClientFinancialEntry(client: any, clientRow: any) {
  if (!clientRow?.id || !clientRow?.user_id || !clientRow?.plano_id) return;

  try {
    const { data: plan } = await client
      .from('plans')
      .select('price')
      .eq('id', clientRow.plano_id)
      .maybeSingle();

    const planPrice = Number(plan?.price || 0);
    const discount = Number(clientRow.desconto || 0);
    const entrada = Math.max(0, planPrice - discount);

    let custo = 0;
    const serverIds = Array.isArray(clientRow.servidores_ids) ? clientRow.servidores_ids : [];

    if (serverIds.length > 0) {
      const { data: servers } = await client
        .from('servidores_iptv')
        .select('valor')
        .in('id', serverIds);

      custo = (servers || []).reduce((sum: number, server: any) => sum + Number(server?.valor || 0), 0);
    }

    const { error } = await client
      .from('transacoes')
      .insert({
        user_id: clientRow.user_id,
        cliente_id: clientRow.id,
        tipo: 'entrada',
        entrada,
        custo,
        valor: entrada,
        data: typeof clientRow.created_at === 'string'
          ? clientRow.created_at.slice(0, 10)
          : new Date().toISOString().slice(0, 10),
        descricao: `Cadastro cliente ${clientRow.id}`,
        serv_id: serverIds[0] || null,
      });

    if (error) {
      console.error('[Financeiro] Erro ao registrar novo cliente:', error);
    } else {
      console.log(`[Financeiro] Entrada criada para novo cliente ${clientRow.id}`);
    }
  } catch (error) {
    console.error('[Financeiro] Falha ao registrar entrada do novo cliente:', error);
  }
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env['SUPABASE_URL'];
  const SUPABASE_SERVICE_ROLE_KEY = process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });

  const originalFrom = client.from.bind(client);

  // The Telegram new-client flow inserts into `clientes` and then calls
  // `.select().single()`. Hook that exact server-side operation so the
  // corresponding financial entry is created without changing the bot flow.
  (client as any).from = (table: string) => {
    const builder = originalFrom(table);
    if (table !== 'clientes') return builder;

    let payload: any = null;

    const wrapBuilder = (target: any): any => new Proxy(target, {
      get(currentTarget, prop, receiver) {
        const original = Reflect.get(currentTarget, prop, receiver);

        if (prop === 'insert' && typeof original === 'function') {
          return (...args: any[]) => {
            payload = Array.isArray(args[0]) ? args[0][0] : args[0];
            return wrapBuilder(original.apply(currentTarget, args));
          };
        }

        if (prop === 'single' && typeof original === 'function') {
          return async (...args: any[]) => {
            const result = await original.apply(currentTarget, args);
            if (!result?.error && result?.data && payload?.status === 'ativo' && payload?.plano_id) {
              await registerNewClientFinancialEntry(client, result.data);
            }
            return result;
          };
        }

        if (typeof original === 'function') {
          return (...args: any[]) => {
            const result = original.apply(currentTarget, args);
            return result && typeof result === 'object' ? wrapBuilder(result) : result;
          };
        }

        return original;
      }
    });

    return wrapBuilder(builder);
  };

  return client;
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
